name: CI

on:
 push:
   branches: [ main ]

jobs:

 build:

   runs-on: ubuntu-latest

   steps:

   - uses: actions/checkout@v4

   - name: Build docker images
     run: docker compose build

   - name: Run containers
     run: docker compose up -d

   - name: Install Newman
     run: npm install -g newman

   - name: Run tests
     run: newman run postman/integration-tests.json
